### ISSUE TITLE
Couldn't find rpy v2.9.5

### ISSUE THREAD

**Issue by benjamin-ping-xu** [tonyduan/hte-prediction-rcts#2]
The most recent version available on Anaconda is v2.9.4, could this be a typo in requirements.txt?

**Comment by tonyduan** [comment]
Actually on PyPI it looks like the latest version is 3.0.4:
https://pypi.org/project/rpy2/

I'd recommend installing via pip. Does that work for you?

**Comment by thequantumpotato** [comment]
Thanks for the response, Tony.

I initially tried installing via the pip command suggested in the README, but encountered an issue with the installation of rpy, which is why I tried Anaconda as an alternative. You are correct that the latest version is 3.0.4. It was my fault for trying to install in a way that was not intended.
